version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 0000
      MYSQL_DATABASE: roadmap
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - my-network  # Connect to the custom network

  springboot-app:
    build:
      context: ./backend        # Use the backend folder as the build context
      dockerfile: Dockerfile      # Explicitly specify the Dockerfile (default name)
    image: mahdi1/springboot-app:latest
    container_name: springboot-app
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/roadmap
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 0000
    ports:
      - "8081:8081"
    restart: always
    networks:
      - my-network  # Connect to the custom network

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: always
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus  # Persistent storage for metrics
    ports:
      - "9090:9090"
    networks:
      - my-network  # Connect to the custom network
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--log.level=info"  # Adjust log level (debug, info, warn, error)
      - "--web.enable-lifecycle"  # Enable API reload without restarting
  
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - my-network  # Connect to the custom network

volumes:
  mysql_data:
  grafana_data:
  prometheus_data:
    driver: local  # Ensures persistent storage

networks:
  my-network:
    driver: bridge  # Default bridge network
