version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 0000
      MYSQL_DATABASE: roadmap
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - my-network

  springboot-app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: mahdi1/springboot-app:latest 
    container_name: springboot-app
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/roadmap
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 0000

    ports:
      - "8081:8081"
    restart: always
    networks:
      - my-network

  prometheus:
    image: prom/prometheus:latest 
    container_name: prometheus
    restart: always
    volumes:

      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./monitoring/alert.rules.yml:/etc/prometheus/alert.rules.yml:ro
      - prometheus_data:/prometheus
    ports:
      - "9090:9090"
    networks:
      - my-network
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--log.level=info"
      - "--web.enable-lifecycle" 

  alertmanager:
    image: prom/alertmanager:latest 
    container_name: alertmanager
    restart: always
    ports:
      - "9093:9093"
    volumes:

      - ./monitoring/alertmanager.yml:/etc/alertmanager/alertmanager.yml:ro
      - ./secrets:/etc/alertmanager/secrets:ro 

    networks:
      - my-network
    command:
      - "--config.file=/etc/alertmanager/alertmanager.yml"
      - "--log.level=info"

  grafana:
    image: grafana/grafana:latest 
    container_name: grafana
    restart: always
    ports:
      - "3000:3000"
    volumes:

      - grafana_data:/var/lib/grafana

    environment:
      pass: 
    networks:
      - my-network

  pushgateway:
    image: prom/pushgateway:latest 
    container_name: pushgateway
    restart: always
    ports:
      - "9091:9091"
    networks:
      - my-network

volumes:
  mysql_data:
  grafana_data:
  prometheus_data:

networks:
  my-network:
    driver: bridge