version: "3.8"

services:
  mysql:
    image: mysql:8.0 # Consider pinning to a more specific version like mysql:8.0.36 for stability
    container_name: mysql-db
    restart: always
    environment:
      # WARNING: Default passwords like '0000' are insecure.
      # For production or sensitive environments, use Docker secrets or inject via environment variables at runtime.
      MYSQL_ROOT_PASSWORD: 0000
      MYSQL_DATABASE: roadmap
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - my-network

  springboot-app:
    build:
      context: ./backend # Assumes 'backend' directory is relative to docker-compose.yml
      dockerfile: Dockerfile
    image: mahdi1/springboot-app:latest # This will be the image built and tagged by Jenkins
    container_name: springboot-app
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/roadmap
      SPRING_DATASOURCE_USERNAME: root
      # WARNING: Default passwords like '0000' are insecure.
      SPRING_DATASOURCE_PASSWORD: 0000
      # PUSHGATEWAY_URL: http://pushgateway:9091 # Uncomment if your app pushes metrics
    ports:
      - "8081:8081"
    restart: always
    networks:
      - my-network

  prometheus:
    image: prom/prometheus:v2.49.1 # Pinned to a specific version for stability (example, check latest stable)
    container_name: prometheus
    restart: always
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./monitoring/alert.rules.yml:/etc/prometheus/alert.rules.yml:ro
      - prometheus_data:/prometheus
    ports:
      - "9090:9090"
    networks:
      - my-network
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--log.level=info"
      - "--web.enable-lifecycle"

  alertmanager:
    image: prom/alertmanager:v0.27.0 # Pinned to a specific version for stability (example, check latest stable)
    container_name: alertmanager
    restart: always
    ports:
      - "9093:9093"
    volumes:
      - ./monitoring/alertmanager.yml:/etc/alertmanager/alertmanager.yml:ro
      - ./secrets:/etc/alertmanager/secrets:ro
      - alertmanager_data:/alertmanager
    networks:
      - my-network
    command:
      - "--config.file=/etc/alertmanager/alertmanager.yml"
      - "--log.level=info"
      - "--storage.path=/alertmanager"

  grafana:
    image: grafana/grafana:10.4.1 # Pinned to a specific version for stability (example, check latest stable)
    container_name: grafana
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      # - ./monitoring/grafana/provisioning:/etc/grafana/provisioning
    environment:
      # Optional: Set admin user/password, disable login form, etc.
      # GF_SECURITY_ADMIN_USER: admin
      # GF_SECURITY_ADMIN_PASSWORD: your_grafana_password
      # GF_AUTH_ANONYMOUS_ENABLED: true
      # GF_AUTH_ANONYMOUS_ORG_ROLE: Viewer
      pass: # Add your Grafana admin password here or use environment variables/secrets
    networks:
      - my-network

  pushgateway:
    image: prom/pushgateway:v1.8.0 # Pinned to a specific version for stability (example, check latest stable)
    container_name: pushgateway
    restart: always
    ports:
      - "9091:9091"
    networks:
      - my-network

volumes:
  mysql_data:
  grafana_data:
  prometheus_data:
  alertmanager_data:

networks:
  my-network:
    driver: bridge