global:
  resolve_timeout: 5m

route:
  # Group alerts primarily by alertname and job.
  group_by: ['alertname', 'job']

  # Default receiver for all alerts.
  receiver: 'email-mahdi'

  # Buffering and timing settings.
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 4h

receivers:
  # Receiver configuration for sending emails to mahdi.bouafif@gmail.com
  - name: 'email-mahdi'
    email_configs:
      - to: 'mahdi.bouafif@gmail.com'
        from: 'MS_eWsEnS@test-z0vklo667qpl7qrx.mlsender.net' 
        smarthost: 'smtp.mailersend.net:587'

        auth_username_file: /etc/alertmanager/secrets/smtp_username
        auth_password_file: /etc/alertmanager/secrets/smtp_password

        # Use TLS encryption 
        require_tls: true
