global:
  resolve_timeout: 5m
  # If you have global SMTP settings that apply to all email receivers,
  # define them here with the 'smtp_' prefix.
  # Example:
  # smtp_smarthost: 'smtp.example.com:587'
  # smtp_from: 'alertmanager@example.com'
  # smtp_require_tls: true

route:
  group_by: ['alertname', 'job']
  receiver: 'email-mahdi'
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 4h

receivers:
  - name: 'email-mahdi'
    email_configs:
      - to: 'mahdi.bouafif@gmail.com' # This is a property of the email_config item

        # These are also properties of THIS email_config item, at the same indentation level as 'to'.
        # They override or specify settings for this particular email notification.
        from: 'MS_eWsEnS@test-z0vklo667qpl7qrx.mlsender.net'
        smarthost: 'smtp.mailersend.net:587'

        # Secret file paths
        auth_username_file: /etc/alertmanager/secrets/smtp_username
        auth_password_file: /etc/alertmanager/secrets/smtp_password
        # auth_identity: if needed for your SMTP provider

        # TLS setting for this email_config
        require_tls: true # Defaults to global.smtp_require_tls if not set, which itself defaults to true.

        # Optional: Customize email subject/body using templates.
        # headers:
        #   Subject: '[ALERT] {{ .CommonLabels.alertname }} for {{ .CommonLabels.job }}'
        # html: '{{ template "email.default.html" . }}'