global:
  resolve_timeout: 5m

route:
  group_by: ['alertname']
  receiver: 'email-config'
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 4h

receivers:
  - name: 'email-config'
    email_configs:
      - to: 'youremail@example.com'
        from: 'alertmanager@example.com'
        smarthost: 'smtp.example.com:587'
        auth_username: 'your_smtp_username'
        auth_password: 'your_smtp_password'
        require_tls: true
