global:
  resolve_timeout: 5m

  # Global SMTP settings
  smtp_from: 'MS_eWsEnS@test-z0vklo667qpl7qrx.mlsender.net'
  smtp_smarthost: 'smtp.mailersend.net:587'

  # SMTP Authentication:
  # Username is provided via the ALERTMANAGER_SMTP_USER environment variable,
  # which is substituted here by Alertmanager.
  # Password is read from the specified file.
  smtp_auth_username: '${ALERTMANAGER_SMTP_USER}' # Uses environment variable
  smtp_auth_password_file: /etc/alertmanager/secrets/smtp_password # Password from file

  # Require TLS for SMTP connections. Defaults to true if not specified.
  smtp_require_tls: true

route:
  group_by: ['alertname', 'job']
  receiver: 'email-mahdi'
  group_wait: 30s           # How long to initially wait to buffer alerts of the same group.
  group_interval: 5m        # How long to wait before sending a notification about new alerts for a group.
  repeat_interval: 4h       # How long to wait before re-sending a notification for an unresolved alert.

receivers:
  - name: 'email-mahdi'
    email_configs:
      - to: 'mahdi.bouafif@gmail.com'
        # This receiver will inherit SMTP settings (from, smarthost, auth, require_tls)
        # from the 'global' section.