global:
  resolve_timeout: 5m
  # No global SMTP settings, as they are defined per receiver.

route:
  group_by: ['alertname', 'job']
  receiver: 'email-mahdi'
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 4h

receivers:
  - name: 'email-mahdi'
    email_configs:
      - to: 'mahdi.bouafif@gmail.com'
        # These all need the smtp_ prefix when defined within email_configs
        smtp_from: 'MS_eWsEnS@test-z0vklo667qpl7qrx.mlsender.net'
        smtp_smarthost: 'smtp.mailersend.net:587'

        # --- CORRECTED Secret File Paths ---
        smtp_auth_username_file: /etc/alertmanager/secrets/smtp_username
        smtp_auth_password_file: /etc/alertmanager/secrets/smtp_password
        # smtp_auth_identity: if needed
        # smtp_auth_secret: if password was plain text (not recommended)

        smtp_require_tls: true

        # Optional: Customize email subject/body using templates.
        # headers:
        #   Subject: '[ALERT] {{ .CommonLabels.alertname }} for {{ .CommonLabels.job }}'
        # html: '{{ template "email.default.html" . }}'