global:
  scrape_interval: 15s

rule_files:
  - "/etc/prometheus/alert.rules.yml"

# Alertmanager configuration

alerting:
  alertmanagers:
    - static_configs:

        - targets: ['alertmanager:9093']

# Your scrape configurations
scrape_configs:
  - job_name: 'springboot-app'
    metrics_path: '/actuator/prometheus'
    static_configs:

      - targets: ['springboot-app:8081']

  # Scrape job for Pushgateway
  - job_name: 'pushgateway'
    honor_labels: true
    static_configs:

      - targets: ['pushgateway:9091']

  # Add a scrape job for Prometheus itself
  - job_name: 'prometheus'
    static_configs:

      - targets: ['localhost:9090']
